# -*- coding: utf-8 -*-
"""Python_Practicals_Comple.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/117dNcYdVXf7RWaadgpq8YxYqgF5rNUYf

## Practical 1
**Aim:** Write Python programs to demonstrate variables, data types (int, float, str, bool) and all operators (Arithmetic, Assignment, Comparison, Logical, Membership, Identity, Bitwise).
"""

# variable and data type
a = 20
b = 5.5
c = "Hello"
d = True

print(a, type(a))
print(b, type(b))
print(c, type(c))
print(d, type(d))

# arithmetic operator
a = 18
b = 5

print("Addition: ", a + b)
print("Subtraction: ", a - b)
print("Multiplication: ", a * b)
print("Division: ", a / b)
print("Modulus: ", a % b)
print("Exponential: ", a ** b)
print("Floor Division: ", a // b)

# assignment operator
a = 20
print("a is: ", a)
a += 7
print("a += 7: ", a)
a -= 4
print("a -= 4: ", a)
a *= 3
print("a *= 3: ", a)
a /= 5
print("a /= 5: ", a)
a %= 5
print("a %= 5: ", a)

# comparison operator
a = 6
b = 4

print("a == b: ", a == b)
print("a >= b: ", a >= b)
print("a <= b: ", a <= b)
print("a > b: ", a > b)
print("a < b: ", a < b)
print("a != b: ", a != b)

# logical operator
a = 6
b = 4

print(a > 5 and b < 10)
print(a > 15 or b < 10)
print(not (a > 5))

# membership operator
fruits = ["apple", "mango"]

print("apple in fruits: ", "apple" in fruits)
print("Orange not in fruits: ", "Orange" not in fruits)
print("Kiwi in fruits: ", "kiwi" in fruits)

# identity operator
a = [1, 2, 3]
b = a
c = [1, 2, 3]

print("a is b: ", a is b)
print("a is c: ", a is c)
print("a is not c: ", a is not c)

# bitwise operator
a = 10
b = 3

print("AND: ", a & b)
print("OR: ", a | b)
print("XOR: ", a ^ b)
print("Left Shift: ", a << 1)
print("Right Shift: ", a >> 1)
print("Not a: ", ~a)

l1 = [15, 25, 35, 25, 45]
l1.append(55)
l1.insert(1, 10)
l1.extend([65, 75])
l1.remove(25)
print("List: ", l1)
print("Pop: ", l1.pop())
print("Index of 35: ", l1.index(35))
print("Count of 25: ", l1.count(25))
l1.reverse()
print("Reversed: ", l1)
l1.sort()
print("Sorted: ", l1)

"""## Practical 2
**Aim:** Demonstrate creation and manipulation of list, tuple, set, dictionary and string with their built-in methods.
"""

# tuple
t1 = (15, 25, 35, 25, 45)
print("Tuple: ", t1)
print("Count of 25: ", t1.count(25))
print("Index of 35: ", t1.index(35))
print("Length: ", len(t1))
print("Slice: ", t1[1:4])

# set
s1 = {2, 4, 6, 8}
s2 = {6, 8, 10, 12}
s1.add(14)
print("Set 1: ", s1)
s1.remove(2)
print("Set 1: ", s1)
print("Union: ", s1.union(s2))
print("Intersect: ", s1.intersection(s2))
print("Difference: ", s1.difference(s2))
print("Symmetric Difference: ", s1.symmetric_difference(s2))
print("Subset: ", {4, 6}.issubset(s1))
print("Disjoint: ", s1.isdisjoint({20, 30}))

# dictionary
d1 = {"name": "Pal", "age": 20, "city": "Surat"}
print("Keys: ", list(d1.keys()))
print("Values: ", list(d1.values()))
print("Items: ", list(d1.items()))
print("Get age: ", d1.get("age"))
print("Pop city: ", d1.pop("city"))
d1.update({"branch": "AI"})
print("Dict: ", d1)

# string
s1 = "data science"
print("Upper: ", s1.upper())
print("Lower: ", s1.lower())
print("Title: ", s1.title())
print("Strip: ", s1.strip())
print("Replace: ", s1.replace("data", "computer"))
print("Find: ", s1.find("science"))
print("Split: ", s1.split())
print("Join: ", "-".join(["x", "y", "z"]))

"""## Practical 3
**Aim:** Implement programs using if, if-else, elif, while loop, for loop, nested loops, and loop control statements (break, continue, pass).
"""

# if
age = 20
if age >= 18:
    print("You are eligible to vote")

# if else
num = 4
if num % 2 == 0:
    print("Even number")
else:
    print("Odd number")

# elif
marks = 75
if marks >= 80:
    print("Grade A")
elif marks < 80 and marks >= 60:
    print("Grade B")
elif marks < 60 and marks >= 33:
    print("Grade C")
else:
    print("Fail")

# while
i = 1
while i <= 5:
    print(i)
    i += 1

# for
for i in range(6):
    print(i)

# nested for
for i in range(2):
    for j in range(3):
        print(i, j)

# break
for i in range(6):
    if i == 3:
        break
    print(i)

# continue
for i in range(6):
    if i == 3:
        continue
    print(i)

# pass
for i in range(6):
    if i == 2:
        pass
    print(i)

"""## Practical 4
**Aim:** Write Python programs using user-defined functions with different argument types and demonstrate use of built-in modules (math, random, statistics).
"""

# without argument without return type
def greet():
    print("Hello world")

greet()

# with argument without return type
def greet(name):
    print("Hello", name)

greet("Pal")

# without argument with return type
def add():
    a = 6
    b = 4
    return a + b

sum_val = add()
print("Addition: ", sum_val)

# with argument with return type
def add(a, b):
    return a + b

sum_val = add(6, 4)
print("Addition: ", sum_val)

# default argument
def greet(name="Pal"):
    print("Hello", name)

greet()

# math,random and statistics function
import math
import random
import statistics

print("Square root of 49: ", math.sqrt(49))
print("Factorial of 6: ", math.factorial(6))
print("Random integer [10, 99]: ", random.randint(10, 99))
num_list = [10, 20, 30, 40, 50, 70]
print("Mean: ", statistics.mean(num_list))

"""## Practical 5
**Aim:** Perform read, write and append operations on text files, CSV files, and binary files using Python.
"""

# text file
f1 = open("message.txt", "w")
f1.write("Welcome to Python programming\n")
f1.write("File Handling in Python")
f1.close()

f1 = open("message.txt", "r")
print("After Writing: ")
print(f1.read())
f1.close()

f1 = open("message.txt", "a")
f1.write("This is appended line\n")
f1.close()

# csv file
import csv

data = [["Id", "Students", "Score"],
        [101, "Pal", 90],
        [102, "Aarya", 85],
        [103, "Nancy", 76]]

f1 = open("marks.csv", "w", newline="")
writer = csv.writer(f1)
writer.writerows(data)
f1.close()

f1 = open("marks.csv", "r")
reader = csv.reader(f1)
for row in reader:
    print(row)
f1.close()

# binary file
bl = open("sample.bin", "wb")
bl.write(b"Python Binary Data")
bl.close()

bl = open("sample.bin", "rb")
print("After writting: ")
print(bl.read())
bl.close()

bl = open("sample.bin", "ab")
bl.write(b"\nAppended Data")
bl.close()

"""## Practical 6
**Aim:** Demonstrate exception handling using try, except, else, finally blocks and raise statement with custom exceptions.
"""

# try,expect,ese and fnally
try:
    n1 = 10
    n2 = 2
    r = n1 / n2
except ZeroDivisionError:
    print("Error: Can't Divide by zero")
else:
    print("Result: ", r)
finally:
    print("Execution completed")

# user define and raise
class AgeError(Exception):
    pass

try:
    age = 15
    if age < 18:
        raise AgeError("Age must be 18 or above")
except AgeError as c:
    print("Custom Exception: ", c)
else:
    print("You are eligible")
finally:
    print("Program Completed")

"""## Practical 7
**Aim:** Connect Python with MySQL database and perform Create, Read, Update and Delete (CRUD) operations.
"""

import sqlite3

# Connect to database
connection = sqlite3.connect("my_database.db")
cursor = connection.cursor()

cursor.execute("""
    CREATE TABLE IF NOT EXISTS students (
        id INT PRIMARY KEY,
        name TEXT,
        age INT,
        course TEXT
    )
""")

sql = "INSERT OR IGNORE INTO students (id, name, age, course) VALUES (?, ?, ?, ?)"
values = [
    (1, "Pal", 20, "Python"),
    (2, "Aarya", 21, "Java"),
    (3, "Nancy", 19, "C++")
]

cursor.executemany(sql, values)
connection.commit()
print("Student inserted !!")

cursor.execute("SELECT * FROM students")
students = cursor.fetchall()
for student in students:
    print(student)

sql = "UPDATE students SET name = ?, age = ?, course = ? WHERE id = ?"
values = ("Nancy", 22, "MySQL", 3)
cursor.execute(sql, values)
connection.commit()
print("Student record updated !!")

cursor.execute("SELECT * FROM students")
students = cursor.fetchall()
for student in students:
    print(student)

sql = "DELETE FROM students WHERE id = ?"
student_id = (2,)
cursor.execute(sql, student_id)
connection.commit()
print("Student record deleted !!")

cursor.execute("SELECT * FROM students")
students = cursor.fetchall()
for student in students:
    print(student)

cursor.close()
connection.close()

"""## Practical 8
**Aim:** Calculate and interpret descriptive statistics: mean, median, mode, variance, standard deviation, range, quartiles and IQR on a given dataset.
"""

import pandas as pd

df = pd.read_csv("employee.csv")

print("Top 5 Records:", df.head())
print("Bottom 5 Records:", df.tail())

print(
    "Integer Datatype Columns:",
    df.select_dtypes(include=["object"]).columns,
)

print("Maximum Monthly Income:", df["MonthlyIncome"].max())
print("Minimum Monthly Income:", df["MonthlyIncome"].min())

print("Measure of Central Tendency:")
print("Mean of Monthly Income:", df["MonthlyIncome"].mean())
print("Median of Monthly Income:", df["MonthlyIncome"].median())
print("Mode of Monthly Income:", df["MonthlyIncome"].mode()[0])

print("Measure of spread:")
print( "Range of Monthly Income:",df["MonthlyIncome"].max() - df["MonthlyIncome"].min(),)
print("Variance:", round(df["MonthlyIncome"].var(), 2))
print("Standard Deviation:", round(df["MonthlyIncome"].std(), 2))

q1 = df["MonthlyIncome"].quantile(0.25)
q2 = df["MonthlyIncome"].quantile(0.50)
q3 = df["MonthlyIncome"].quantile(0.75)
iqr = q3 - q1

print("Quantile 1 (25%):", q1)
print("Quantile 2 (50%):", q2)
print("Quantile 3 (75%):", q3)
print("Interquartile Range:", iqr)

print("Correlation coefficient:")
print(
    "Age vs Monthly Income:",
    df["Age"].corr(df["MonthlyIncome"]),
)

"""## Practical 9
**Aim:** Demonstrate the data science life cycle and perform Univariate,
Bivariate and Multivariate analysis on a real-world dataset.
"""



"""## Practical 10
**Aim:** Demonstrate NumPy array creation, indexing, slicing, reshaping, broadcasting and mathematical operations on multidimensional arrays.
"""

import numpy as np
# creating
a1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("Array is:", a1)
print("Zero grid:", np.zeros((2, 4)))
print("Ones grid:", np.ones((2, 3)))
print("Even numbers:", np.arange(0, 12).reshape(3, 4))
print("Equispaced:", np.linspace(0, 1, 10).reshape(2, 5))

# indexing,slicing,reshaping and broadcasting
print("Element at row 2, column 3:", a1[1, 2])
print("First row:", a1[0, :])
print("Second row:", a1[1, :])

print("First two rows:", a1[:2, :])
print("Last two columns:", a1[:, 1:])
print("First column:", a1[:, 0])

a2 = np.arange(1, 13).reshape(3, 4)
print("Reshaped Array (3x4):", a2)

a3 = np.array([10, 20, 30])
print("Addition of array 1 and 3:", a1 + a3)
print("Floor division:", a3 // 5)

# mathamatical operation
print("Addition:", a1 + a2[:3, :3])
print("Subtraction:", a1 - 2)
print("Multiplication:", a1 * 3)
print("Division:", a1 / 2)
print("Square:", a1**2)

"""## Practical 11
**Aim:** Use Pandas to create Series and DataFrames, perform data selection, filtering, grouping and aggregation operations.
"""

import pandas as pd

# Create Series
marks = pd.Series([85, 72, 90, 65, 78])
print("Series: ", marks)

# Create DataFrame
data = {
    "Name": ["pal", "Aarya", "Nancy", "Zeel", "Ruchita", "Pari"],
    "Department": ["Computer", "IT", "Computer", "IT", "Computer", "IT"],
    "Marks": [85, 72, 90, 65, 78, 88],
    "Age": [20, 21, 22, 21, 20, 20],
}
df = pd.DataFrame(data)
print("Dataframe: ", df)

# select
print("Select name and marks column:\n", df[["Name", "Marks"]])
print("Select first two rows:\n", df.iloc[:2])
print("Marks of index 2:", df.loc[2, "Marks"])

# filter
print(
    "Student with marks greater than 80 and age 20:\n",
    df[(df["Marks"] > 80) & (df["Age"] == 20)],
)
print("Student from IT department:\n", df[df["Department"] == "IT"])

# grouping and agreegation
print("Group by departments of Student:")
grouped = df.groupby("Department")
print(grouped["Marks"].mean())

print("Average Marks: ", df["Marks"].mean())
print("Maximum age: ", df["Age"].max())
print("Minimum age: ", df["Age"].min())
print("Total Marks: ", df["Marks"].sum())
print("Multiple aggregation:")
print(df.groupby("Department")["Marks"].agg(["mean", "sum"]))

"""## Practical 12
**Aim:** Use SciPy's stats module to compute statistical measures and perform statistical tests on datasets.
"""

import numpy as np
from scipy import stats

d1 = np.array([12, 15, 14, 10, 18, 20, 15, 16, 14, 13])
d2 = np.array([10, 12, 11, 14, 13, 15, 12, 16, 11, 15])

print("Dataset 1: ", d1)
print("Dataset 2: ", d2)

print("Descriptive Statistics:")
r = stats.describe(d1)
print("Number of observation:", r.nobs)
print("Minimum:", r.minmax[0])
print("Maximum:", r.minmax[1])
print("Mean:", r.mean)
print("Variance:", r.variance)
print("Skewness:", r.skewness)
print("Kurtosis:", r.kurtosis)

print("Normal Distribution")
mean = np.mean(d1)
std = np.std(d1)
x = 15

print("Mean: ", mean)
print("Standard deviation: ", std)
print("PDF: ", stats.norm.pdf(x, mean, std))
print("CDF: ", stats.norm.cdf(x, mean, std))

print("Independent T-Test:")
t_stat, p_value = stats.ttest_ind(d1, d2)
print("T-statistics:", t_stat)
print("P-value:", p_value)

if p_value < 0.05:
    print("Significance difference between two datasets")
else:
    print("No Significance difference between two datasets")

print("Pearson Correlation:")
correlation, p_value = stats.pearsonr(d1, d2)
print("Correlation Coefficient:", correlation)
print("P-value:", p_value)

if p_value < 0.05:
    print("Correlation is statistically significant.")
else:
    print("Correlation is not statistically significant.")

"""## Practical 13
**Aim:** Extract and parse data from an HTML document or web page using BeautifulSoup library.
"""

from bs4 import BeautifulSoup
import requests

search_query = "laptops"

for page_no in range(1, 3):

    url = f"https://www.flipkart.com/search?q={search_query}&page={page_no}"
    print("Fetching URL:", url)

    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
                      "AppleWebKit/537.36 (KHTML, like Gecko) "
                      "Chrome/120.0.0.0 Safari/537.36"
    }

    res = requests.get(url, headers=headers)

    if res.status_code == 200:

        soup = BeautifulSoup(res.text, "html.parser")

        # Current-style product containers
        products = soup.select("div[data-id]")

        if not products:
            print("No products found on the page")
            continue

        count = 0

        for item in products:
            text = item.get_text(" ", strip=True)

            if text:
                print("Product:", text[:200])
                print("-" * 40)

                count += 1

            if count == 4:
                break

        print("Page no:", page_no)

    else:
        print("Failed to fetch page. Status code:", res.status_code)

"""## Practical 14
**Aim:** Demonstrate basic machine learning workflow using Scikitlearn:
data loading, splitting, model training and evaluation.
"""

# Data Loading
import pandas as pd
df = pd.read_csv("Recipe Reviews and User Feedback Dataset.csv")
features = [
    "user_reputation",
    "reply_count",
    "thumbs_up",
    "thumbs_down",
    "best_score"
]
X = df[features]
y = df["stars"]
print("Dataset Shape:", df.shape)
print("Total Records:", len(df))
print("Feature Count:", X.shape[1])
print("Prediction Target: stars")
print("\nSample Records:")
print(X.head())

# data cleaning
print("Missing Values in Dataset:")
print(df.isnull().sum())
data = df.copy()
initial_count = len(data)
data_cleaned = data.dropna().drop_duplicates().reset_index(drop=True)
print("\nInitial Records :", initial_count)
print("Cleaned Records :", len(data_cleaned))
print("Records Removed :", initial_count - len(data_cleaned))
X = data_cleaned[features]
y = data_cleaned["stars"]

# data spliting
from sklearn.model_selection import train_test_split
y_binary = (y >= 4).astype(int)
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y_binary,
    test_size=0.20,
    random_state=42,
    stratify=y_binary
)
print("Total Records :", len(X))
print("Training Records :", len(X_train))
print("Testing Records :", len(X_test))
print("Number of Features :", X_train.shape[1])

# model training
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)
model.fit(X_train, y_train)
print("Model Training Completed Successfully!")
print("Model:", model)

# model evalution
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)

print("Model Accuracy:", round(accuracy * 100, 2), "%")

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(
    y_test,
    y_pred,
    target_names=["Low Rating (0)", "Good Rating (1)"]
))

# prediction
sample_review = X_test.iloc[[0]]

actual_class = y_test.iloc[0]
predicted_class = model.predict(sample_review)[0]

print("Sample Review Features:")
print(sample_review)

print("\nActual Rating Class:",
      "Good (1)" if actual_class == 1 else "Low (0)")

print("Predicted Rating Class:",
      "Good (1)" if predicted_class == 1 else "Low (0)")

"""## Practical 15
**Aim:** Compute and visualize Binomial and Poisson probability
distributions using SciPy and Matplotlib.

## Practical 16
**Aim:** Plot and analyze Normal and Exponential continuous probability
distributions and demonstrate the Central Limit Theorem.

## Practical 17
**Aim:** Perform hypothesis testing using one sample t-test and interpret
results based on p-value and significance level.

## Practical 18
**Aim:** Perform data cleaning operations: detect and handle missing values,
remove duplicate records, and treat outliers in a dataset
"""

import pandas as pd
import numpy as np

# Load dataset
df = pd.read_csv("diabetic_data.csv", na_values="?")

print("Initial Shape:", df.shape)
df.head()

# 1. Detect & Handle Missing Values
missing = df.isnull().sum()

print("\nMissing values per column:")
print(missing[missing > 0])

for col in df.select_dtypes(include="object"):
    if df[col].isnull().any():
        df[col] = df[col].fillna(df[col].mode()[0])

print("\nRemaining missing values:", df.isnull().sum().sum())

# 2. Detect & Remove Duplicate Records
print("\nDuplicate records:", df.duplicated().sum())

df.drop_duplicates(inplace=True)

print("Shape after removing duplicates:", df.shape)

# 3. Detect & Treat Outliers using IQR

numeric_cols = df.select_dtypes(include=np.number).columns

for col in numeric_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    outliers = ((df[col] < lower) | (df[col] > upper)).sum()

    print(col, ":", outliers)

    # Treat outliers by capping
    df[col] = df[col].clip(lower, upper)

print("Outliers treated successfully.")

# Treat outliers by capping
df[col] = df[col].clip(lower, upper)

print("Outliers treated successfully.")
print("Final Shape:", df.shape)
df.head()

"""## Practical 19
**Aim:** Apply data preprocessing techniques: slicing, filtering, sorting,
concatenating, aggregating and normalizing data using Pandas.
"""

import pandas as pd
import numpy as np
# Load dataset
df = pd.read_csv("diabetic_data.csv", na_values="?")

# 1. Slicing
print("Slicing:")
print(df.loc[0:4, ["race", "gender", "age", "time_in_hospital"]])

# 2. Filtering
print("Filtering:")
filtered = df[df["time_in_hospital"] > 5]
print(filtered[["age", "gender", "time_in_hospital"]].head())

# 3. Sorting
print("Sorting:")
sorted_df = df.sort_values("num_medications", ascending=False)
print(sorted_df[["age", "num_medications"]].head())

# 4. Concatenating
part1 = df[["encounter_id", "age", "gender"]].head(5)
part2 = df[["encounter_id", "age", "gender"]].tail(5)

combined = pd.concat([part1, part2])
print("Concatenated Data:")
print(combined)

# 5. Aggregating
print("Aggregation:")
aggregation = df.groupby("gender")["time_in_hospital"].agg(["mean", "min", "max", "count"])
print(aggregation)

# 6. Normalizing
print("Normalization:")
df["normalized_medications"] = (
    (df["num_medications"] - df["num_medications"].min()) /
    (df["num_medications"].max() - df["num_medications"].min())
)
print(df[["num_medications", "normalized_medications"]].head())

"""## Practical 20
**Aim:** Create various types of plots using Matplotlib: line plot, bar chart,
histogram, pie chart, scatter plot using subplots and figure
properties.
"""

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("diabetic_data.csv", na_values="?")

# line plot
mean_stay = df.groupby("age")["time_in_hospital"].mean()
plt.figure(figsize=(8, 5))
plt.plot(mean_stay.index, mean_stay.values, marker="o")
plt.title("Average Hospital Stay by Age")
plt.xlabel("Age Group")
plt.ylabel("Average Hospital Stay")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# bar chart
admission_count = df["admission_type_id"].value_counts().sort_index()
plt.figure(figsize=(8, 5))
plt.bar(admission_count.index.astype(str), admission_count.values)
plt.title("Patients by Admission Type")
plt.xlabel("Admission Type ID")
plt.ylabel("Number of Patients")
plt.show()

# histogram
plt.figure(figsize=(7, 5))
plt.hist(df["num_medications"].dropna(), bins=20)
plt.title("Distribution of Number of Medications")
plt.xlabel("Number of Medications")
plt.ylabel("Frequency")
plt.show()

# pie chart
readmitted = df["readmitted"].value_counts()
plt.figure(figsize=(7, 5))
plt.pie(readmitted.values,
        labels=readmitted.index,
        autopct="%1.1f%%")
plt.title("Readmission Distribution")
plt.show()

# scatter plot
sample = df[["num_lab_procedures", "num_medications"]].dropna().head(1000)
plt.figure(figsize=(7, 5))
plt.scatter(sample["num_lab_procedures"], sample["num_medications"], alpha=0.5)
plt.title("Lab Procedures vs Medications")
plt.xlabel("Number of Lab Procedures")
plt.ylabel("Number of Medications")
plt.show()